name: im_chat_common_plugin
description: "A new Flutter project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.6.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^5.0.0-release-candidate-9.3.2
  plugin_platform_interface: ^2.0.2
  intl: ^0.19.0
  dio: ^5.3.3
  intl_translation:
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.9
  sentry_dio: ^8.6.0
  sentry_flutter: ^8.12.0
  flutter_smart_dialog: ^4.9.7+7 # dialog
  flutter_easyloading: ^3.0.5
  flutter_screenutil: ^5.9.0 # make app responsive
  shimmer: ^3.0.0 # shimmer
  common_utils: ^2.1.0 # utils
  flutter_html: ^3.0.0-beta.2
  shared_preferences: ^2.3.3
  package_info_plus: ^8.3.0
  logger: ^2.0.2+1
  encrypt: ^5.0.3
  pretty_dio_logger: ^1.3.1
  badges: ^3.1.2
  form_builder_file_picker: ^4.3.0
  flutter_animate: ^4.5.2
  flutter_form_builder: ^9.7.0
  step_progress_indicator: ^1.0.2
  group_button: ^5.3.4 # button group
  flutter_image_compress: ^2.1.0
  video_compress: ^3.1.3
  dotted_border: ^2.1.0
  image_cropper: ^9.1.0
  path_provider: ^2.1.5
  heif_converter: ^1.0.0
  image: ^4.2.0
  dropdown_button2: ^2.3.9
  flutter_cache_manager: ^3.4.1
  archive: ^4.0.2
  url_launcher: ^6.3.1
  image_gallery_saver_plus: ^4.0.1

  easy_refresh: ^3.4.0
  flutter_keyboard_visibility: ^6.0.0
  scrollable_positioned_list: 0.2.3
  lpinyin: ^2.0.2
  get_storage: ^2.1.1
  cached_network_image: ^3.4.1
  permission_handler: ^12.0.0+1
  
  bot_toast: ^4.1.3 #提示
  image_picker:
    git:
      url: https://github.com/xiaoli55979/tools_plugins.git
      ref: main
      path: image_picker/image_picker

  wukongimfluttersdk:
    git:
      url: https://github.com/xiaoli55979/tools_plugins.git
      ref: main
      path: WuKongIMFlutterSDK
  device_info:
    git:
      url: https://github.com/xiaoli55979/tools_plugins.git
      ref: main
      path: device_info
  flutter_scankit:
    git:
      url: https://github.com/xiaoli55979/tools_plugins.git
      ref: main
      path: flutter-scankit
  line_detection_plugin:
    git:
      url: https://github.com/xiaoli55979/tools_plugins.git
      ref: main
      path: line_detection_plugin
  permission_utils:
    git:
      url: https://github.com/xiaoli55979/tools_plugins.git
      ref: main
      path: permission_utils
  dio_smart_retry:
    git:
      url: https://github.com/xiaoli55979/tools_plugins.git
      ref: main
      path: dio_smart_retry
  adaptive_action_sheet:
    git:
      url: https://github.com/xiaoli55979/tools_plugins.git
      ref: main
      path: adaptive_action_sheet
  im_chat_resource_plugin:
    path: ../../im_chat_project_plugins/im_chat_resource_plugin
  flutter_screen_lock_plug:
    git:
      url: https://github.com/xiaoli55979/tools_plugins.git
      ref: main
      path: flutter_screen_lock_plug

dev_dependencies:
#  flutter_test:
#    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.example.im_chat_common_plugin
        pluginClass: ImChatCommonPlugin
      ios:
        pluginClass: ImChatCommonPlugin

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package

  generate: true
  assets:
    - assets/
