name: im_chat_settings_plugin
description: "A new Flutter project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.6.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  qr_flutter: ^4.1.0
  common_utils: ^2.1.0
  get: ^5.0.0-release-candidate-9.3.2
  plugin_platform_interface: ^2.0.2
  url_launcher: ^6.3.1
  open_filex: ^4.6.0
  path_provider: ^2.1.5
  im_chat_common_plugin:
    path: ../../im_chat_project_plugins/im_chat_common_plugin
#  flutter_screen_lock_plug:
#    path: ../../flutter_screen_lock_plug
  flutter_screen_lock_plug:
    git:
      url: https://github.com/xiaoli55979/tools_plugins.git
      ref: main
      path: flutter_screen_lock_plug
dev_dependencies:
#  flutter_test:
#    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: com.example.im_chat_settings_plugin
        pluginClass: ImChatSettingsPlugin
      ios:
        pluginClass: ImChatSettingsPlugin

build:
  obfuscate: true
  dart-obfuscation: full

