//  This file is automatically generated. DO NOT EDIT, all your changes would be lost.
//  https://pub.dartlang.org/packages/iconfont_convert

import 'package:flutter/material.dart';

class IconFont {
  static const String _family = 'iconfont';
  static const String _package = 'google_components_plugin';
  
  IconFont._();
  
  static const IconData guge = IconData(0xe82f, fontFamily: _family, fontPackage: _package); // google
  static const IconData tousujianyi = IconData(0x100c2, fontFamily: _family, fontPackage: _package); // 投诉建议
  static const IconData yijianjianyi = IconData(0xe631, fontFamily: _family, fontPackage: _package); // 意见建议
  static const IconData shenfenzheng_6_copy_copy = IconData(0xfef0, fontFamily: _family, fontPackage: _package); // 身份证-copy-copy
  static const IconData shenfenzhengzhengmian_2_copy = IconData(0xfeef, fontFamily: _family, fontPackage: _package); // 身份证正面
  static const IconData shenfenzhengrenzheng = IconData(0xe687, fontFamily: _family, fontPackage: _package); // 身份证认证
  static const IconData a_frame_39 = IconData(0xe603, fontFamily: _family, fontPackage: _package); // 攻略/选中
  static const IconData jiaoyiliebiao = IconData(0xe602, fontFamily: _family, fontPackage: _package); // 交易列表
  static const IconData kefu_1 = IconData(0xeeb4, fontFamily: _family, fontPackage: _package); // 客服
  static const IconData jiaoyi = IconData(0xfdc0, fontFamily: _family, fontPackage: _package); // 交易
  static const IconData a_kefufuwu = IconData(0xe62a, fontFamily: _family, fontPackage: _package); // 客服，服务
  static const IconData a_gonglve_2 = IconData(0xfde1, fontFamily: _family, fontPackage: _package); // 攻略 
  static const IconData lvyougonglve = IconData(0xfeed, fontFamily: _family, fontPackage: _package); // 旅游攻略
  static const IconData kefu = IconData(0xe640, fontFamily: _family, fontPackage: _package); // 客服
  static const IconData chenggong = IconData(0xe64e, fontFamily: _family, fontPackage: _package); // 成功
  static const IconData quxiao = IconData(0xe676, fontFamily: _family, fontPackage: _package); // 取消
  static const IconData liulanqi = IconData(0xe661, fontFamily: _family, fontPackage: _package); // 浏览器
  static const IconData fangda = IconData(0xe63d, fontFamily: _family, fontPackage: _package); // 放大
  static const IconData fangda_1 = IconData(0xe60e, fontFamily: _family, fontPackage: _package); // 放大
  static const IconData tongzhi = IconData(0xe606, fontFamily: _family, fontPackage: _package); // 通知
  static const IconData ap_pxiazai = IconData(0xe6fd, fontFamily: _family, fontPackage: _package); // APP下载
  static const IconData qinglihuancun = IconData(0xe607, fontFamily: _family, fontPackage: _package); // 清理缓存
  static const IconData suoxiao = IconData(0xe658, fontFamily: _family, fontPackage: _package); // 缩小
  static const IconData banbenxinxi = IconData(0xe653, fontFamily: _family, fontPackage: _package); // 版本信息
  static const IconData shuzirenminbi = IconData(0xe60c, fontFamily: _family, fontPackage: _package); // 数字人民币
  static const IconData usdt = IconData(0xe7f8, fontFamily: _family, fontPackage: _package); // USDT
  static const IconData tupian = IconData(0xfc23, fontFamily: _family, fontPackage: _package); // 图片
  static const IconData shouye = IconData(0xfc24, fontFamily: _family, fontPackage: _package); // 首页
  static const IconData gouwuche = IconData(0xfc27, fontFamily: _family, fontPackage: _package); // 购物车
  static const IconData paizhao = IconData(0xfc29, fontFamily: _family, fontPackage: _package); // 拍照
  static const IconData tishi = IconData(0xfc2c, fontFamily: _family, fontPackage: _package); // 提示
  static const IconData wenjian = IconData(0xfc2d, fontFamily: _family, fontPackage: _package); // 文件
  static const IconData wode = IconData(0xfc2e, fontFamily: _family, fontPackage: _package); // 我的
  static const IconData xiaoxi = IconData(0xfc2f, fontFamily: _family, fontPackage: _package); // 消息
  static const IconData gonggao = IconData(0xfc30, fontFamily: _family, fontPackage: _package); // 公告
  static const IconData hongbao = IconData(0xfc31, fontFamily: _family, fontPackage: _package); // 红包
  static const IconData shezhi = IconData(0xfc33, fontFamily: _family, fontPackage: _package); // 设置
  static const IconData wenzhang = IconData(0xfc34, fontFamily: _family, fontPackage: _package); // 文章
  static const IconData youhuiquan_1 = IconData(0xfc35, fontFamily: _family, fontPackage: _package); // 优惠券
  static const IconData anquanyanzheng = IconData(0xfc36, fontFamily: _family, fontPackage: _package); // 安全验证
  static const IconData sousuo = IconData(0xfc3a, fontFamily: _family, fontPackage: _package); // 搜索
  static const IconData yiwen = IconData(0xfc3b, fontFamily: _family, fontPackage: _package); // 疑问
  static const IconData kabao = IconData(0xfc3e, fontFamily: _family, fontPackage: _package); // 卡包
  static const IconData renwu = IconData(0xfc3f, fontFamily: _family, fontPackage: _package); // 任务
  static const IconData shuju = IconData(0xfc40, fontFamily: _family, fontPackage: _package); // 数据
  static const IconData anquan = IconData(0xfc42, fontFamily: _family, fontPackage: _package); // 安全
  static const IconData chakandingdan = IconData(0xfc43, fontFamily: _family, fontPackage: _package); // 查看订单
  static const IconData gouwu = IconData(0xfc44, fontFamily: _family, fontPackage: _package); // 购物
  static const IconData youjian = IconData(0xfc45, fontFamily: _family, fontPackage: _package); // 邮件
  static const IconData luxiang = IconData(0xfc49, fontFamily: _family, fontPackage: _package); // 录像
  static const IconData jiesuo = IconData(0xfc50, fontFamily: _family, fontPackage: _package); // 解锁
  static const IconData mima = IconData(0xfc51, fontFamily: _family, fontPackage: _package); // 密码
  static const IconData yinhangka_1 = IconData(0xfc54, fontFamily: _family, fontPackage: _package); // 银行卡
  static const IconData chongzhi = IconData(0xfc56, fontFamily: _family, fontPackage: _package); // 充值
  static const IconData yue = IconData(0xfc57, fontFamily: _family, fontPackage: _package); // 余额
  static const IconData guanyuwomen = IconData(0xfc59, fontFamily: _family, fontPackage: _package); // 关于我们
  static const IconData shijian = IconData(0xfc5e, fontFamily: _family, fontPackage: _package); // 时间
  static const IconData saomiao = IconData(0xfc61, fontFamily: _family, fontPackage: _package); // 扫描
  static const IconData shanchu = IconData(0xfc62, fontFamily: _family, fontPackage: _package); // 删除
  static const IconData renzheng = IconData(0xfc6b, fontFamily: _family, fontPackage: _package); // 认证
  static const IconData wendang = IconData(0xfc6c, fontFamily: _family, fontPackage: _package); // 文档
  static const IconData history = IconData(0xfc6f, fontFamily: _family, fontPackage: _package); // 历史记录
  static const IconData zijin = IconData(0xe6f4, fontFamily: _family, fontPackage: _package); // 资金
  static const IconData daiban = IconData(0xe701, fontFamily: _family, fontPackage: _package); // 待办
  static const IconData forward_zhuanfa = IconData(0xe614, fontFamily: _family, fontPackage: _package); // forward-转发
  static const IconData cart_gouwuche = IconData(0xe615, fontFamily: _family, fontPackage: _package); // Cart-购物车
  static const IconData order_dingdan = IconData(0xe616, fontFamily: _family, fontPackage: _package); // order-订单
  static const IconData a_customerservice_kefu = IconData(0xe617, fontFamily: _family, fontPackage: _package); // customer service-客服
  static const IconData gongjijin = IconData(0xf72f, fontFamily: _family, fontPackage: _package); // 公积金
  static const IconData goupiao = IconData(0xf732, fontFamily: _family, fontPackage: _package); // 购票
  static const IconData kaijuzhengming = IconData(0xf740, fontFamily: _family, fontPackage: _package); // 开具证明
  static const IconData shenfenzheng = IconData(0xf74d, fontFamily: _family, fontPackage: _package); // 身份证
  static const IconData tongzhigonggao = IconData(0xf756, fontFamily: _family, fontPackage: _package); // 通知公告
  static const IconData yinsijimi = IconData(0xf761, fontFamily: _family, fontPackage: _package); // 隐私机密
  static const IconData youhuiquan = IconData(0xf762, fontFamily: _family, fontPackage: _package); // 优惠券
  static const IconData zixun = IconData(0xf766, fontFamily: _family, fontPackage: _package); // 咨询
  static const IconData piaoju = IconData(0xe685, fontFamily: _family, fontPackage: _package); // 021_票据
  static const IconData zhifubao = IconData(0xe808, fontFamily: _family, fontPackage: _package); // 支付宝
  static const IconData weixin = IconData(0xe809, fontFamily: _family, fontPackage: _package); // 微信
  static const IconData bank = IconData(0xe80a, fontFamily: _family, fontPackage: _package); // 银行卡
  static const IconData security = IconData(0xe80b, fontFamily: _family, fontPackage: _package); // 021_安全
  static const IconData edit = IconData(0xe80c, fontFamily: _family, fontPackage: _package); // 021_编辑-25
  static const IconData share = IconData(0xe80d, fontFamily: _family, fontPackage: _package); // 021_分享-24
  static const IconData video = IconData(0xe80e, fontFamily: _family, fontPackage: _package); // 021_视频
  static const IconData search = IconData(0xe810, fontFamily: _family, fontPackage: _package); // 021_搜索
  static const IconData delete = IconData(0xe811, fontFamily: _family, fontPackage: _package); // 021_删除
  static const IconData camera = IconData(0xe812, fontFamily: _family, fontPackage: _package); // 021_拍摄
  static const IconData star = IconData(0xe813, fontFamily: _family, fontPackage: _package); // 021_收藏-03
  static const IconData bank_2 = IconData(0xe814, fontFamily: _family, fontPackage: _package); // 021_银行卡-19
  static const IconData message = IconData(0xe815, fontFamily: _family, fontPackage: _package); // 021_消息
  static const IconData picture = IconData(0xe816, fontFamily: _family, fontPackage: _package); // 021_照片
  static const IconData setup = IconData(0xe817, fontFamily: _family, fontPackage: _package); // 021_设置
  static const IconData file = IconData(0xe818, fontFamily: _family, fontPackage: _package); // 021_文件
  static const IconData person_card = IconData(0xe819, fontFamily: _family, fontPackage: _package); // 021_证件
  static const IconData home = IconData(0xe820, fontFamily: _family, fontPackage: _package); // 021_主页
}

class _PreviewIcon {
  const _PreviewIcon(this.icon, this.name, this.propName);

  final IconData icon;
  final String name;
  final String propName;
}

class IconFontPreview extends StatelessWidget {
  const IconFontPreview({Key? key}) : super(key: key);

  static const iconList = <_PreviewIcon>[
    _PreviewIcon(IconFont.guge, "guge", "google"),
    _PreviewIcon(IconFont.tousujianyi, "tousujianyi", "投诉建议"),
    _PreviewIcon(IconFont.yijianjianyi, "yijianjianyi", "意见建议"),
    _PreviewIcon(IconFont.shenfenzheng_6_copy_copy, "shenfenzheng_6_copy_copy", "身份证-copy-copy"),
    _PreviewIcon(IconFont.shenfenzhengzhengmian_2_copy, "shenfenzhengzhengmian_2_copy", "身份证正面"),
    _PreviewIcon(IconFont.shenfenzhengrenzheng, "shenfenzhengrenzheng", "身份证认证"),
    _PreviewIcon(IconFont.a_frame_39, "a_frame_39", "攻略/选中"),
    _PreviewIcon(IconFont.jiaoyiliebiao, "jiaoyiliebiao", "交易列表"),
    _PreviewIcon(IconFont.kefu_1, "kefu_1", "客服"),
    _PreviewIcon(IconFont.jiaoyi, "jiaoyi", "交易"),
    _PreviewIcon(IconFont.a_kefufuwu, "a_kefufuwu", "客服，服务"),
    _PreviewIcon(IconFont.a_gonglve_2, "a_gonglve_2", "攻略 "),
    _PreviewIcon(IconFont.lvyougonglve, "lvyougonglve", "旅游攻略"),
    _PreviewIcon(IconFont.kefu, "kefu", "客服"),
    _PreviewIcon(IconFont.chenggong, "chenggong", "成功"),
    _PreviewIcon(IconFont.quxiao, "quxiao", "取消"),
    _PreviewIcon(IconFont.liulanqi, "liulanqi", "浏览器"),
    _PreviewIcon(IconFont.fangda, "fangda", "放大"),
    _PreviewIcon(IconFont.fangda_1, "fangda_1", "放大"),
    _PreviewIcon(IconFont.tongzhi, "tongzhi", "通知"),
    _PreviewIcon(IconFont.ap_pxiazai, "ap_pxiazai", "APP下载"),
    _PreviewIcon(IconFont.qinglihuancun, "qinglihuancun", "清理缓存"),
    _PreviewIcon(IconFont.suoxiao, "suoxiao", "缩小"),
    _PreviewIcon(IconFont.banbenxinxi, "banbenxinxi", "版本信息"),
    _PreviewIcon(IconFont.shuzirenminbi, "shuzirenminbi", "数字人民币"),
    _PreviewIcon(IconFont.usdt, "usdt", "USDT"),
    _PreviewIcon(IconFont.tupian, "tupian", "图片"),
    _PreviewIcon(IconFont.shouye, "shouye", "首页"),
    _PreviewIcon(IconFont.gouwuche, "gouwuche", "购物车"),
    _PreviewIcon(IconFont.paizhao, "paizhao", "拍照"),
    _PreviewIcon(IconFont.tishi, "tishi", "提示"),
    _PreviewIcon(IconFont.wenjian, "wenjian", "文件"),
    _PreviewIcon(IconFont.wode, "wode", "我的"),
    _PreviewIcon(IconFont.xiaoxi, "xiaoxi", "消息"),
    _PreviewIcon(IconFont.gonggao, "gonggao", "公告"),
    _PreviewIcon(IconFont.hongbao, "hongbao", "红包"),
    _PreviewIcon(IconFont.shezhi, "shezhi", "设置"),
    _PreviewIcon(IconFont.wenzhang, "wenzhang", "文章"),
    _PreviewIcon(IconFont.youhuiquan_1, "youhuiquan_1", "优惠券"),
    _PreviewIcon(IconFont.anquanyanzheng, "anquanyanzheng", "安全验证"),
    _PreviewIcon(IconFont.sousuo, "sousuo", "搜索"),
    _PreviewIcon(IconFont.yiwen, "yiwen", "疑问"),
    _PreviewIcon(IconFont.kabao, "kabao", "卡包"),
    _PreviewIcon(IconFont.renwu, "renwu", "任务"),
    _PreviewIcon(IconFont.shuju, "shuju", "数据"),
    _PreviewIcon(IconFont.anquan, "anquan", "安全"),
    _PreviewIcon(IconFont.chakandingdan, "chakandingdan", "查看订单"),
    _PreviewIcon(IconFont.gouwu, "gouwu", "购物"),
    _PreviewIcon(IconFont.youjian, "youjian", "邮件"),
    _PreviewIcon(IconFont.luxiang, "luxiang", "录像"),
    _PreviewIcon(IconFont.jiesuo, "jiesuo", "解锁"),
    _PreviewIcon(IconFont.mima, "mima", "密码"),
    _PreviewIcon(IconFont.yinhangka_1, "yinhangka_1", "银行卡"),
    _PreviewIcon(IconFont.chongzhi, "chongzhi", "充值"),
    _PreviewIcon(IconFont.yue, "yue", "余额"),
    _PreviewIcon(IconFont.guanyuwomen, "guanyuwomen", "关于我们"),
    _PreviewIcon(IconFont.shijian, "shijian", "时间"),
    _PreviewIcon(IconFont.saomiao, "saomiao", "扫描"),
    _PreviewIcon(IconFont.shanchu, "shanchu", "删除"),
    _PreviewIcon(IconFont.renzheng, "renzheng", "认证"),
    _PreviewIcon(IconFont.wendang, "wendang", "文档"),
    _PreviewIcon(IconFont.history, "history", "历史记录"),
    _PreviewIcon(IconFont.zijin, "zijin", "资金"),
    _PreviewIcon(IconFont.daiban, "daiban", "待办"),
    _PreviewIcon(IconFont.forward_zhuanfa, "forward_zhuanfa", "forward-转发"),
    _PreviewIcon(IconFont.cart_gouwuche, "cart_gouwuche", "Cart-购物车"),
    _PreviewIcon(IconFont.order_dingdan, "order_dingdan", "order-订单"),
    _PreviewIcon(IconFont.a_customerservice_kefu, "a_customerservice_kefu", "customer service-客服"),
    _PreviewIcon(IconFont.gongjijin, "gongjijin", "公积金"),
    _PreviewIcon(IconFont.goupiao, "goupiao", "购票"),
    _PreviewIcon(IconFont.kaijuzhengming, "kaijuzhengming", "开具证明"),
    _PreviewIcon(IconFont.shenfenzheng, "shenfenzheng", "身份证"),
    _PreviewIcon(IconFont.tongzhigonggao, "tongzhigonggao", "通知公告"),
    _PreviewIcon(IconFont.yinsijimi, "yinsijimi", "隐私机密"),
    _PreviewIcon(IconFont.youhuiquan, "youhuiquan", "优惠券"),
    _PreviewIcon(IconFont.zixun, "zixun", "咨询"),
    _PreviewIcon(IconFont.piaoju, "piaoju", "021_票据"),
    _PreviewIcon(IconFont.zhifubao, "zhifubao", "支付宝"),
    _PreviewIcon(IconFont.weixin, "weixin", "微信"),
    _PreviewIcon(IconFont.bank, "bank", "银行卡"),
    _PreviewIcon(IconFont.security, "security", "021_安全"),
    _PreviewIcon(IconFont.edit, "edit", "021_编辑-25"),
    _PreviewIcon(IconFont.share, "share", "021_分享-24"),
    _PreviewIcon(IconFont.video, "video", "021_视频"),
    _PreviewIcon(IconFont.search, "search", "021_搜索"),
    _PreviewIcon(IconFont.delete, "delete", "021_删除"),
    _PreviewIcon(IconFont.camera, "camera", "021_拍摄"),
    _PreviewIcon(IconFont.star, "star", "021_收藏-03"),
    _PreviewIcon(IconFont.bank_2, "bank_2", "021_银行卡-19"),
    _PreviewIcon(IconFont.message, "message", "021_消息"),
    _PreviewIcon(IconFont.picture, "picture", "021_照片"),
    _PreviewIcon(IconFont.setup, "setup", "021_设置"),
    _PreviewIcon(IconFont.file, "file", "021_文件"),
    _PreviewIcon(IconFont.person_card, "person_card", "021_证件"),
    _PreviewIcon(IconFont.home, "home", "021_主页"),
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('IconFont'),
      ),
      body: GridView.count(
        shrinkWrap: true,
        crossAxisCount: 4,
        children: iconList.map((e) {
          return InkWell(
            onTap: () {
              //
            },
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Container(
                  margin: const EdgeInsets.only(bottom: 8),
                  child: Icon(e.icon),
                ),
                Text(e.name, style: const TextStyle(fontSize: 12), overflow: TextOverflow.ellipsis, maxLines: 1),
                Text(e.propName, style: const TextStyle(fontSize: 12), overflow: TextOverflow.ellipsis, maxLines: 1),
              ],
            ),
          );
        }).toList(),
      ),
    );
  }
}
