arb-dir: lib/l10n
output-dir: lib/l10n/localization
template-arb-file: intl_zh.arb
output-localization-file: kit_client_localizations.dart
output-class: KitClientLocalizations
header-file: header.txt
synthetic-package: false
untranslated-messages-file: untranslated.txt
