name: im_chat_conversation_plugin
description: "A new Flutter project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.6.1
  flutter: '>=3.3.0'
dependencies:
  flutter:
    sdk: flutter
  lottie: ^3.3.1
#  audio_session: ^0.2.1
#  flutter_sound: ^9.28.0
  permission_handler: ^12.0.0+1
  record: ^6.0.0
  intl: ^0.19.0
  plugin_platform_interface: ^2.0.2
  emoji_picker_flutter: ^3.1.0 # 表情包管理
  open_filex: ^4.6.0
  path_provider: ^2.1.5
  file_picker: ^8.1.3
  video_player: ^2.9.2
  video_thumbnail: ^0.5.3
  flutter_popup: ^3.3.0
  mime: ^2.0.0
  just_audio: ^0.9.46
#  image_picker: ^1.1.2
  screenshot_callback_plus: ^1.0.0  # 截屏检测
  flutter_advanced_avatar: ^1.5.2
  get: ^5.0.0-release-candidate-9.3.2
  provider: ^6.1.5
  permission_utils:
    git:
      url: https://github.com/xiaoli55979/tools_plugins.git
      ref: main
      path: permission_utils
#    path: ../../permission_utils
#  flutter_scankit:
#    path: ../../flutter-scankit

  image_picker:
    git:
      url: https://github.com/xiaoli55979/tools_plugins.git
      ref: main
      path: image_picker/image_picker
    #  flutter_chat_ui: ^1.6.15
    #  使用本地库是因为线上库消息事件长按无法传出坐标

  flutter_chat_ui:
#    git:
#      url: https://github.com/xiaoli55979/tools_plugins.git
#      ref: wb_dev
      path: ../../tools_plugins/flutter_chat_ui

  im_chat_common_plugin:
    path: ../../im_chat_project_plugins/im_chat_common_plugin

dev_dependencies:

  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.example.im_chat_conversation_plugin
        pluginClass: ImChatConversationPlugin
      ios:
        pluginClass: ImChatConversationPlugin

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
